;;; theme-darcula --- custom theme
;;; Commentary:

;;; Code:

(deftheme darcula
  "custom theme")

(custom-theme-set-faces
 'darcula

 ;; default colors
 '(black ((t (:foreground "#000000"))))
 '(red ((t (:foreground "#cd0000"))))
 '(green ((t (:foreground "#00cd00"))))
 '(yellow ((t (:foreground "#cdcd00"))))
 '(blue ((t (:foreground "#0000ee"))))
 '(magenta ((t (:foreground "#cd00cd"))))
 '(cyan ((t (:foreground "#00cdcd"))))
 '(white ((t (:foreground "#e5e5e5"))))
 '(brightblack ((t (:foreground "#7f7f7f"))))
 '(brightred ((t (:foreground "#ff0000"))))
 '(brightgreen ((t (:foreground "#00ff00"))))
 '(brightyellow ((t (:foreground "#ffff00"))))
 '(brightblue ((t (:foreground "#5c5cff"))))
 '(brightcyan ((t (:foreground "#ff00ff"))))
 '(brightwhite ((t (:foreground "#ffffff"))))

 ;; *** custom faces (built-in) ***
 ;; background, font-color, cursor
 '(cursor ((t (:foreground "#5f5fd7"))))
 '(default ((t (:background "#000000" :foreground "#e5e5e5"))))

 ;; region
 '(region ((t (:background "#870000"))))

 ;; mode line
 '(mode-line ((t (:background "#444444" :foreground "#e5e5e5"))))
 '(mode-line-buffer-id ((t (:background "#444444" :foreground "#ffffff"))))
 '(mode-line-emphasis ((t (:bold t :weight bold))))
 '(mode-line-highlight ((t (:box (:line-width 2 :color "#444444" :style released-button)))))
 '(mode-line-inactive ((t (:background "#303030" :foreground "#c6c6c6" :box (:line-width -1 :color "#444444" :style nil) :weight light))))

 '(bold ((t (:bold t :weight bold))))
 '(bold-italic ((t (:italic t :bold t :slant italic :weight bold))))
 '(border ((t (:background "#000000"))))
 '(buffer-menu-buffer ((t (:bold t :weight bold))))
 '(button ((t (:underline t))))
 '(completions-annotations ((t (:italic t :slant italic))))
 '(completions-common-part ((t (:foundry "outline" :width normal :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#e5e5e5" :background "#000000" :stipple nil))))
 '(completions-first-difference ((t (:bold t :weight bold))))
 '(cursor ((t (:background "#5f5fd7"))))
 '(escape-glyph ((t (:foreground "#00cdcd"))))
 '(file-name-shadow ((t (:foreground "#a8a8a8"))))
 '(fixed-pitch ((t (nil))))
 '(font-lock-builtin-face ((t (:foreground "#5f5fdf"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#cd0000"))))
 '(font-lock-comment-face ((t (:foreground "#af0000"))))
 '(font-lock-constant-face ((t (:foreground "#d75f00"))))
 '(font-lock-doc-face ((t (:foreground "#af0000"))))
 '(font-lock-doc-string-face ((t (:foreground "#af8700"))))
 '(font-lock-function-name-face ((t (:foreground "#00afaf"))))
 '(font-lock-keyword-face ((t (:foreground "#5f5fff"))))
 '(font-lock-negation-char-face ((t (nil))))
 '(font-lock-preprocessor-face ((t (:foreground "#5c5cff"))))
 '(font-lock-reference-face ((t (:foreground "#00cdcd"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#5faf5f"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#00ff00"))))
 '(font-lock-string-face ((t (:foreground "#cdcd00"))))
 '(font-lock-type-face ((t (:foreground "#00ff00"))))
 '(font-lock-variable-name-face ((t (:foreground "#5fd75f"))))
 '(font-lock-warning-face ((t (:foreground "#cd0000"))))
 '(fringe ((t (:background "#121212"))))
 '(header-line ((t (:background "#121212" :foreground "#ffffff" :inverse-video nil :underline nil))))
 '(help-argument-name ((t (nil))))
 '(highlight ((t (:background "#00005f" :foreground "#e5e5e5"))))
 '(isearch ((t (:background "#0000ee"))))
 '(isearch-fail ((t (:background "#870000"))))
 '(italic ((t (:italic t :slant italic))))
 '(lazy-highlight ((t (:background "#870000" :foreground "#e5e5e5"))))
 '(link ((t (:foreground "#00cdcd" :underline t))))
 '(link-visited ((t (:foreground "#cd00cd" :underline t))))
 '(match ((t (:background "#5f5fd7"))))
 '(menu ((t (:foreground "#121212" :background "#ffffff"))))
 '(minibuffer-prompt ((t (:bold t :foreground "#5f5fd7" :weight bold))))
 '(mouse ((t (:background "#000000"))))
 '(next-error ((t (:background "#000087" :foreground "#e5e5e5"))))
 '(nobreak-space ((t (:foreground "#00cdcd" :underline t))))
 '(query-replace ((t (:background "#0000d7"))))
 '(scroll-bar ((t (:foreground "#c6c6c6")))) ;; defualt: "systemscrollbar"
 '(secondary-selection ((t (:background "#5f5fd7"))))
 '(shadow ((t (:foreground "#a8a8a8"))))
 '(tool-bar ((t (:foreground "#000000" :box (:line-width 1 :style released-button)))))
 '(tooltip ((t (:background "#121212" :foreground "#ffffff"))))
 '(trailing-whitespace ((t (:background "#d70000"))))
 '(underline ((t (:underline t))))
 '(variable-pitch ((t (nil))))
 '(vertical-border ((t (:background "#303030" :foreground "#c6c6c6" :box (:line-width -1 :color "#444444" :style nil) :weight light))))

 ;; custom-faces (etc)
 '(border-glyph ((t (nil))))
 '(buffers-tab ((t (:background "#000000" :foreground "#e5e5e5"))))
 '(change-log-acknowledgement ((t (:foreground "#cd0000"))))
 '(change-log-conditionals ((t (:bold t :foreground "#e5e5e5" :weight bold))))
 '(change-log-date ((t (:foreground "#5c5cff"))))
 '(change-log-email ((t (:bold t :foreground "#e5e5e5" :weight bold))))
 '(change-log-file ((t (:foreground "#5f87af"))))
 '(change-log-function ((t (:bold t :foreground "#e5e5e5" :weight bold))))
 '(change-log-list ((t (:foreground "#00ffff"))))
 '(change-log-name ((t (:foreground "#ffff00"))))
 '(custom-button-face ((t (nil))))
 '(custom-changed-face ((t (:background "#0000ee" :foreground "#e5e5e5"))))
 '(custom-documentation-face ((t (nil))))
 '(custom-face-tag-face ((t (:underline t))))
 '(custom-group-tag-face ((t (:foreground "#5c5cff" :underline t))))
 '(custom-group-tag-face-1 ((t (:foreground "#ff00ff" :underline t))))
 '(custom-invalid-face ((t (:background "#cd0000" :foreground "#cdcd00"))))
 '(custom-modified-face ((t (:background "#0000ee" :foreground "#e5e5e5"))))
 '(custom-rogue-face ((t (:background "#000000" :foreground "#ffafff"))))
 '(custom-saved-face ((t (:underline t))))
 '(custom-set-face ((t (:background "#e5e5e5" :foreground "#0000ee"))))
 '(custom-state-face ((t (:foreground "#5fd75f"))))
 '(custom-variable-button-face ((t (:bold t :underline t :weight bold))))
 '(custom-variable-tag-face ((t (:foreground "#0000ee" :underline t))))
 '(develock-bad-manner ((t (:background "#cdcd00" :foreground "#000000"))))
 '(develock-lonely-parentheses ((t (:background "#7f7f7f" :foreground "#0000ee"))))
 '(develock-long-line-1 ((t (:foreground "#d75f00"))))
 '(develock-long-line-2 ((t (:background "#121212" :foreground "#cd0000"))))
 '(develock-reachable-mail-address ((t (:background "#cdcd00" :foreground "#00cd00"))))
 '(develock-upper-case-attribute ((t (:background "#005f00" :foreground "#000000"))))
 '(develock-upper-case-tag ((t (:background "#00005f" :foreground "#000000"))))
 '(develock-whitespace-1 ((t (:background "#cd0000"))))
 '(develock-whitespace-2 ((t (:background "#d75f00"))))
 '(develock-whitespace-3 ((t (:background "#cdcd00"))))
 '(gui-button-face ((t (:background "#c6c6c6" :foreground "#000000"))))
 '(gui-element ((t (:background "#d7d7af" :foreground "#000000"))))
 '(highlight-changes-delete-face ((t (:foreground "#cd0000" :underline t))))
 '(highlight-changes-face ((t (:foreground "#cd0000"))))
 '(highline-face ((t (:background "#0000d7"))))
 '(info-menu-5 ((t (:underline t))))
 '(info-node ((t (:bold t :foreground "#5f5faf" :underline t :weight bold))))
 '(info-xref ((t (:foreground "#5f5fd7" :underline t))))
 '(isearch-secondary ((t (:foreground "#870000"))))
 '(list-mode-item-selected ((t (:background "#5f5faf" :foreground "#e5e5e5"))))
 '(minibuffer-prompt ((t (:foreground "#5f5fd7" :bold t))))
 '(message-cited-text-face ((t (:foreground "#e5e5e5"))))
 '(message-header-cc-face ((t (:foreground "#5f87af"))))
 '(message-header-name-face ((t (:foreground "#e5e5e5"))))
 '(message-header-newsgroups-face ((t (:bold t :foreground "#0000ee" :weight bold))))
 '(message-header-other-face ((t (:foreground "#5f5faf"))))
 '(message-header-subject-face ((t (:bold t :foreground "#5f87af" :weight bold))))
 '(message-header-to-face ((t (:bold t :foreground "#5f87af" :weight bold))))
 '(message-header-xheader-face ((t (:foreground "#0000ee"))))
 '(message-separator-face ((t (:foreground "#875f00"))))
 '(modeline-mousable ((t (:background "#000087" :foreground "#e5e5e5"))))
 '(modeline-mousable-minor-mode ((t (:background "#000087" :foreground "#e5e5e5"))))
 '(outline-1 ((t (:foreground "#5f87af"))))
 '(outline-2 ((t (:bold t :foreground "#0000af" :weight bold))))
 '(outline-3 ((t (:foreground "#00ffff"))))
 '(outline-4 ((t (:foreground "#ffaf00"))))
 '(outline-5 ((t (:foreground "#cd0000"))))
 '(outline-6 ((t (:foreground "#ffff00"))))
 '(outline-7 ((t (:foreground "#0000ee"))))
 '(outline-8 ((t (:foreground "#5c5cff"))))
 '(pointer ((t (nil))))
 '(right-margin ((t (nil))))
 '(show-paren-match ((t (:background "#000087"))))
 '(show-paren-mismatch ((t (:background "#870000"))))
 '(text-cursor ((t (:background "#cdcd00" :foreground "#000000"))))
 '(vertical-divider ((t (nil))))
 '(widget ((t (nil))))
 '(widget-button ((t (:bold t :weight bold))))
 '(widget-button-pressed ((t (:background "#000000" :foreground "#cd0000"))))
 '(widget-documentation ((t (:background "#e5e5e5" :foreground "#00cd00"))))
 '(widget-field ((t (:background "#dadada" :foreground "#000000"))))
 '(widget-inactive ((t (:background "#cd0000" :foreground "#7f7f7f"))))
 '(widget-single-line-field ((t (:background "#dadada" :foreground "#000000"))))

 ;; eshell
 ;;'(eshell-prompt-face ((t (:foreground "green"))))
)

;; autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'darcula)

;;; theme-darcula.el ends here
